#!/usr/bin/env rake

$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)

task :default do
  system 'rake --tasks'
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.test_files = FileList['test/**/*_test.rb']
  test.verbose = true
  # test.warning = true
end
